const FIXED_NUMBER = require("./fixedNumber");

const GLODAO_ROOT_CODE = "5mWd4O";

const GLODAO_BASE_ADDRESS = "0x7a05CE29a44cA8dD49D967367F98D3F07E204faC";

const TWEET_MIN_WORDS_COUNT = 5;

module.exports = {
  FIXED_NUMBER,
  GLODAO_ROOT_CODE,
  GLODAO_BASE_ADDRESS,
  TWEET_MIN_WORDS_COUNT,
};
